exports.chatMessagesForEvent = {
  "Kick off": [
    "Let's get this party started!",
    "Here we go, the match begins!",
    "So excited for today's game!",
    "Time to see who's the best!",
    "Kick off hype!",
    "I got my popcorn, let's do this!",
    "Who's ready for a showdown?",
    "GL HF everyone!",
    "Here we go, zero to zero, anything can happen!",
    "The tension is real right now.",
    "I'm cheering for the home team!",
    "The atmosphere is electric here!",
    "Can't wait to see some great plays!",
    "Ready for an action-packed match!",
    "Go teams, let's go!",
    "Don't blink. This is going to be good.",
    "Oh yeah, big day for soccer!",
    "Let's see who scores first!",
    "Take your seats, folks, it's starting!",
    "I've been waiting all week for this match!",
    "Heard both teams have been training hard!",
    "Coach said they're trying new tactics!",
    "I hope we see an early goal!",
    "Huge crowd in the stadium today!",
    "Drinks and snacks on the table, let's do it!",
    "The energy is amazing!",
    "Match of the year? Possibly!",
    "Fingers crossed for a fair match!",
    "Here come the players on the pitch!",
    "The ref gets us underway!",
    "Can't believe it's finally here!",
    "Ready for the biggest rivalry of the season!",
    "Everyone's eyes on the ball now!",
    "Testing the waters in these first minutes!",
    "Go big or go home!",
    "Been a fan for years, so excited!",
    "This is going to be epic!",
    "Will we see an early defensive slip?",
    "Hoping for a solid performance!",
    "Counting down, and...Started!",
    "Teams are pumped, let's go!",
    "My heart is pounding already!",
    "All eyes on the center circle!",
    "They huddle, let's see if that helps!",
    "Come on, let's get a decisive start!",
    "No second chances, let's do this right!",
    "Stadium looks packed!",
    "It's showtime!",
    "Is it me, or is the energy at 100%?",
    "We are live, folks!"
  ],
  "Fan excitement": [
    "Wow, that was amazing!",
    "Yesss! Loving the energy!",
    "Can't believe that just happened!",
    "So much hype right now!",
    "Keep it coming!",
    "This is what we came to see!",
    "Absolutely brilliant!",
    "Buzzing right now, best atmosphere ever!",
    "I'm on the edge of my seat!",
    "This crowd is incredible!",
    "The fans are going wild!",
    "Never seen such unity in the stands!",
    "They're chanting so loud!",
    "My adrenaline is through the roof!",
    "That play was sensational!",
    "Hands in the air, wave them like we don't care!",
    "The tension just skyrocketed!",
    "Pure euphoria right now!",
    "These supporters are unstoppable!",
    "That moment had me jumping!",
    "So much passion in one place!",
    "This is peak entertainment!",
    "Almost knocked over my drink cheering!",
    "What a moment to witness!",
    "Words can't describe how I feel!",
    "The stadium is a sea of excitement!",
    "Deafening roar from the stands!",
    "Chills all over my body!",
    "My heart is racing right now!",
    "Just when you think it can't get better!",
    "Give me more of this hype!",
    "Cameras flashing everywhere!",
    "Unbelievable rally from the fans!",
    "I love seeing this level of support!",
    "That was a goosebumps moment!",
    "I can feel the vibration through the TV!",
    "Anyone else freaking out right now?",
    "Nothing beats a live crowd!",
    "They must feel unstoppable with this backing!",
    "This is next-level support!",
    "Ref can barely hear the whistle!",
    "Raising the roof with these cheers!",
    "Absolutely on fire!",
    "Incredible energy, can't put it into words!",
    "That's how you show your love for the team!",
    "Electrifying crowd, oh my!",
    "Nobody's sitting down now!",
    "My living room is shaking from the cheers!",
    "No place I'd rather be right now!"
  ],
  "Goal": [
    "GOOOOAAALLL!!",
    "He found the net! Incredible shot!",
    "That's how you do it!",
    "Top corner, unstoppable!",
    "What a strike, unstoppable rocket!",
    "They're celebrating like crazy!",
    "That was pure class right there!",
    "Goal of the season candidate, maybe?",
    "The crowd erupts in celebration!",
    "Keeper stood no chance!",
    "That's one for the highlight reel!",
    "Boom! Just like that, they're ahead!",
    "Finally, a breakthrough!",
    "That pass was perfect, the finish even better!",
    "I've never seen a goal like that before!",
    "Absolutely clinical finishing!",
    "They carved open the defense!",
    "Speechless, that was beautiful!",
    "Team synergy pays off big time!",
    "The fans are going ballistic!",
    "A real poacher's goal!",
    "Well-deserved lead, they've been pushing!",
    "Schoolyard skills on display!",
    "Strike from distance, unstoppable rocket!",
    "Keeper is furious with the defense!",
    "Everyone's hugging in the stands!",
    "Pure pandemonium on the pitch!",
    "This changes everything!",
    "Pinpoint accuracy from the forward!",
    "Yes! I've been waiting for that moment!",
    "All that pressure finally pays off!",
    "He hits the net, game on!",
    "Unbelievable technique there!",
    "The stadium is roaring!",
    "Great build-up, perfect finish!",
    "Coach is ecstatic on the sideline!",
    "What a time to score!",
    "So calm under pressure!",
    "That might seal the deal!",
    "Caught the defense sleeping!",
    "At last, we see the deadlock broken!",
    "This is what the fans came to see!",
    "He read the defense like a book!",
    "The bench is celebrating wild!",
    "So many cheers all around!",
    "They needed that spark, here it is!",
    "Massive goal, unstoppable!",
    "Takes the lead, unstoppable finish!",
    "The scoreboard is lighting up!"
  ],
  "Fan frustration": [
    "What was that?!",
    "Come on, ref, open your eyes!",
    "This is unbelievable!",
    "We need a better performance!",
    "Not again... so frustrating!",
    "I'm losing my patience here!",
    "The crowd is angry, me included!",
    "That's a complete disaster!",
    "Worst call I've seen all season!",
    "Nothing is going our way...",
    "How could we miss that chance?!",
    "The defense is crumbling!",
    "We need a change now, coach!",
    "Can someone fix this mess?",
    "So many sloppy passes!",
    "Tensions are boiling over!",
    "This is painful to watch!",
    "Zero focus out there!",
    "I'm about to rage quit!",
    "We can do better than this!",
    "Fans are booing so loud!",
    "We deserved more from that play!",
    "Rough day on the pitch, folks!",
    "That was a fiasco!",
    "We're getting robbed here!",
    "Why can't we hold possession?!",
    "I can't believe what I'm seeing!",
    "Heads need to roll for this!",
    "Stop giving the ball away!",
    "This is absolutely dire!",
    "The frustration is real!",
    "We've lost all momentum!",
    "We look so disorganized!",
    "No fight left in them, apparently!",
    "Where's the passion?!",
    "I might switch the channel soon!",
    "This is heartbreak city!",
    "Everything going wrong at once!",
    "I'm steaming mad right now!",
    "We need a miracle to turn this around!",
    "Anyone got a backup plan?",
    "Enough with the sloppy mistakes!",
    "Fans are not happy, booing everywhere!",
    "That shot was way off! Ugh!",
    "What are we even doing?!",
    "This is embarrassing!",
    "We can't catch a break!",
    "Somebody fix this meltdown!"
  ],
  "Five minutes remaining": [
    "Just five more minutes, let's go!",
    "Almost at the end, push through!",
    "Come on, final stretch!",
    "We need a late goal here!",
    "This is it, everything on the line!",
    "Time is running out!",
    "Desperation time, folks!",
    "Every second counts now!",
    "We can't afford any mistakes!",
    "The clock is ticking fast!",
    "One last surge, let's do it!",
    "Give it all you've got!",
    "Final push for the win!",
    "Let's see who's got the stamina!",
    "Clutch time, no holding back!",
    "Last chance to turn this around!",
    "So tense, can't handle this pressure!",
    "Ref... let them play, no more calls!",
    "This is going down to the wire!",
    "They're going to throw everything forward!",
    "Bracing ourselves for a dramatic ending!",
    "One moment of magic could change it all!",
    "Hold on to your seats!",
    "Don't blink, final moments here!",
    "We need some heroics now!",
    "Come on, let's not lose hope!",
    "We've come this far, finish strong!",
    "The tension is through the roof now!",
    "One goal could seal the deal!",
    "I'm biting my nails here!",
    "They better keep their heads cool!",
    "Let's not concede in the dying minutes!",
    "This is the big test of nerves!",
    "Five minutes is an eternity in soccer!",
    "Attack or defend? Big call, coach!",
    "No regrets, leave it all on the field!",
    "Fans are chanting like crazy now!",
    "Lung-busting runs incoming!",
    "We can do this, believe!",
    "I'd hate extra time, let's finish now!",
    "Who's stepping up to be the hero?",
    "The final countdown has started!",
    "Shake off the fatigue, keep going!",
    "Don't let them snatch it away!",
    "One last chance to make it count!",
    "Time is almost up, do something!"
  ],
  "End match": [
    "That's the final whistle!",
    "The game is over, folks!",
    "Well, that was intense!",
    "What a match, I'm exhausted!",
    "GG everyone, thanks for watching!",
    "Can't believe it's done!",
    "Some game that was, wow!",
    "Final score locked in!",
    "It all ends here!",
    "What a rollercoaster of emotions!",
    "Time to celebrate or commiserate!",
    "Hands shaken, heads held high!",
    "Till next time, folks!",
    "That was one for the books!",
    "What a finish to a thrilling match!",
    "Sigh of relief on both sides!",
    "Final scoreboard doesn't lie!",
    "We gave it our best shot!",
    "Victory for one, heartbreak for another!",
    "End of the road for now!",
    "Thanks for the memories, team!",
    "I'll catch you all next match!",
    "I'm still buzzing from all that action!",
    "They left it all on the pitch!",
    "Time to wrap it up, see ya!",
    "That was a showstopper!",
    "Ref calls time, game over!",
    "Such drama until the last second!",
    "The fans are either celebrating or in tears!",
    "Appreciate the effort from both teams!",
    "I need to catch my breath!",
    "Let's talk about that next time!",
    "We saw some incredible plays!",
    "Closing time, folks!",
    "All that's left is the post-match analysis!",
    "We can only imagine next week's rematch!",
    "So much to unpack after that match!",
    "Signing off, the match is done!",
    "We have our result: done and dusted!",
    "Hope you all enjoyed that!",
    "Game, set, match, brilliant stuff!",
    "No more to see, folks!",
    "We'll see you again soon!",
    "Everyone can relax now, phew!",
    "It's a wrap, folks!",
    "And that's all she wrote!",
    "Well played, time for a break!"
  ]
};
